### ISSUE TITLE
[BUG] 客户端运行时报错

### ISSUE THREAD

**Issue by DemonKHH** [wechaty/go-wechaty#103]
客户端运行错误信息：
puppet start err:  PuppetService Start() rejection: rpc error: code = Unknown desc = TypeError [ERR_INVALID_ARG_TYPE]: The "listener" argument must be of type function. Received undefined
![image](https://user-images.githubusercontent.com/40262925/145202445-c6a7007a-7a4c-45b7-845a-7d61228fce2f.png)
客户端 golang 代码
![image](https://user-images.githubusercontent.com/40262925/145203320-2efb1ed8-562e-4bdd-ae65-94031f6640d1.png)

服务端运行错误信息：
![image](https://user-images.githubusercontent.com/40262925/145204344-67957325-3c5b-426c-b9cd-62b0f78d4b3f.png)

docker 使用的 lastest 和 next 版本都均会报错
![image](https://user-images.githubusercontent.com/40262925/145202832-16ed3c55-e5f7-47a1-93f1-da0bc7b19ffd.png)

**Comment by DemonKHH** [comment]
低版本 docker 可以使用（目前测试到可以使用的docker版本为 0.67 ）

**Comment by huan** [comment]
According to your error message, if you are using token gateway with PadLocal puppet, then I guess it's related to 

- https://github.com/padlocal/wechaty-puppet-padlocal/issues/117
