### ISSUE TITLE
[BUG]room.MemberAll 返回的列表有问题

### ISSUE THREAD

**Issue by chasonnchen** [wechaty/go-wechaty#111]
问题：
room.MemberAll 获得所有人列表， 发消息at时没有效果

代码：
![image](https://user-images.githubusercontent.com/74540195/162037263-7ce245c2-9ddf-4a9e-b10c-5a8cba37f4b0.png)

日志：
![image](https://user-images.githubusercontent.com/74540195/162037481-f8fedc27-bac6-45b8-a6c3-c8ffbf397969.png)

**Comment by dchaofei** [comment]
1. 请确认下 room.MemberAll 是否获取到了群成员？
2. 你用的是什么 puppet ？

**Comment by chasonnchen** [comment]
1 索取列表之后就打log了，看起来只获取到了自己
2 是用的 padlocal

**Comment by dchaofei** [comment]
那问题是没有获取到群成员，而不是@没效果，  你不妨遍历下获取到的群成员列表打印下，看获取到了什么

**Comment by chasonnchen** [comment]
> 那问题是没有获取到群成员，而不是@没效果， 你不妨遍历下获取到的群成员列表打印下，看获取到了什么

您看上面截图，直接打印，自己获取到了，另一个就报地址有问题了（测试群只有两个人），我稍后遍历打印试试。

**Comment by dchaofei** [comment]
另外 @ 要把机器人自己过滤掉

**Comment by chasonnchen** [comment]
> 另外 @ 要把机器人自己过滤掉

嗯嗯。这个就是功能细节了好说～

**Comment by dchaofei** [comment]
@chasonnchen 现在还有问题吗？

**Comment by chasonnchen** [comment]
> 

问题仍然存在，没有定位到具体原因，我这边就先不实现 @all 这个功能了

附上咱们在群里聊天记录
![8ed92cb3c398e85efcd764feb8871f5](https://user-images.githubusercontent.com/74540195/163145438-753c156a-9a95-4017-b1f2-2414dbc3ace1.jpg)


我的项目地址：https://github.com/chasonnchen/wechat_bot

**Comment by dchaofei** [comment]
@chasonnchen 这个问题已经修复，请升级到 v0.3.9
