### ISSUE TITLE
调用Puppet().Stop()会出现invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by xiangyaoan** [wechaty/go-wechaty#121]
请问能不能提供一个Stop方法用于正常关闭bot ，现在通过Puppet().Stop() 关闭的话，因为autoReconnectGrpcConn()的存在，会导致程序panic
panic: runtime error: invalid memory address or nil pointer dereference
goroutine 275 [running]:
google.golang.org/grpc.(*ClientConn).GetState(0x0, 0x0)
github.com/wechaty/go-wechaty/wechaty-puppet-service.(*PuppetService).autoReconnectGrpcConn(0xc002501b30)
created by github.com/wechaty/go-wechaty/wechaty-puppet-service.(*PuppetService).startGrpcClient

**Comment by dchaofei** [comment]
已经修复：https://github.com/wechaty/go-wechaty/pull/122

请升级到 v0.4.1
