### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by xiangyaoan** [wechaty/go-wechaty#125]
使用的wechaty是 docker 0.78
调用 message.Recall()
 ERR PuppetServiceImpl grpcError() messageRecall() rejection: Cannot read properties of undefined (reading 'clientmsgid')

**Comment by dchaofei** [comment]
用的什么puppet?

**Comment by dchaofei** [comment]
请提供下复现代码

**Comment by xiangyaoan** [comment]
用的 puppet-padlocal

**Comment by xiangyaoan** [comment]
用的 docker wechaty/wechaty:0.78 + puppet-padlocal 0.41版本，在onMessage 中调用 message.Recall()

**Comment by dchaofei** [comment]
从你的描述看似乎是在撤回别人发的消息

**Comment by xiangyaoan** [comment]
是在自己发送的内容中使用的
![image](https://user-images.githubusercontent.com/15627071/168505525-6e3a2642-c1df-4136-9c7d-cec929f9e279.png)

**Comment by dchaofei** [comment]
可以测试下这段代码？

```
	selfMsg, err := message.Say("dong")
	if err != nil {
		log.Println(err)
		return
	}
	isRecall, err := selfMsg.Recall()
	if err != nil {
		log.Println(isRecall, err)
		return 
	}
```

**Comment by xiangyaoan** [comment]
测试了一把在群里发言
![image](https://user-images.githubusercontent.com/15627071/168509439-41908144-29cd-4a13-b781-6beaf6681478.png)

**Comment by dchaofei** [comment]
你使用的是最新的 go-wechaty 版本吗？v0.4.x

**Comment by dchaofei** [comment]
我使用 go-wecahty v0.4.2 + wechaty 镜像  wechaty/wechaty:1.19 测试我发的代码是没问题的

**Comment by xiangyaoan** [comment]
是的
![image](https://user-images.githubusercontent.com/15627071/168510826-d55f3e6a-9913-449a-8836-86dd3baae588.png)

**Comment by xiangyaoan** [comment]
那我升级试试，感谢

**Comment by xiangyaoan** [comment]
升级后可以了，顺便问下，只有用 message.Say 发出的内容才能recall 是吧。就是用做机器人的微信账号通过pc端发言内容无法撤回

**Comment by dchaofei** [comment]
我看了 padlocal 的源码，看起来是只有通过程序发出的才能正常撤回

**Comment by xiangyaoan** [comment]
从pc端发的信息调用，感觉上是wechaty取字段和go-wechaty没对上
![image](https://user-images.githubusercontent.com/15627071/168515093-6f8f4b65-32a7-4207-8ebb-7ef1c870b488.png)

**Comment by dchaofei** [comment]
你可以看下 puppet-padlocal 的代码，撤回消息会从缓存中找 revokeinfo, 而这个 revokeinfo 是只有发送消息时才会存入缓存

https://github.com/wechaty/puppet-padlocal/blob/6eef8d8d2a8487ec719ba3181ff5c36c13e45293/src/puppet-padlocal.ts#L1488

https://github.com/wechaty/puppet-padlocal/blob/6eef8d8d2a8487ec719ba3181ff5c36c13e45293/src/puppet-padlocal.ts#L1488

**Comment by xiangyaoan** [comment]
好的，感谢大佬帮助！

**Comment by dchaofei** [comment]
@xiangyaoan 我发现升级 wechaty/wechaty:1.19 会导致死循环，需要把 go-wechaty 升级到 v0.4.3 可以修复这个问题
