### ISSUE TITLE
[BUG]企微发送小程序失败

### ISSUE THREAD

**Issue by aiscrm** [wechaty/go-wechaty#128]
使用企微token发送小程序失败，报错信息： rpc error: code = Internal desc = Unexpected end of JSON input
go版本：1.17和1.18都试过。
发送的的schema类似如下，也试过很多其他写法，都是不行：
```go
schemas.MiniProgramPayload{
    Appid:       "gh_9eeb94f7c465@app",
    Description: "红荔村i",
    PagePath:    "pages/common/home/main.html",
    Title:       "红荔村i",
    Username:    "wx4c6330912e747939",
    IconUrl:     "http://wx.qlogo.cn/mmhead/Q3auHgzwzM7Uq0FZic3jTSjm07OohygOHWLSw0R2vuhpuiavApLiaBia9A/96",
    ThumbUrl:    "http://wx.qlogo.cn/mmhead/Q3auHgzwzM7Uq0FZic3jTSjm07OohygOHWLSw0R2vuhpuiavApLiaBia9A/96",
}
```

<img width="1917" alt="image" src="https://user-images.githubusercontent.com/30600079/169676608-367e6e06-c568-4922-aba5-f3d23285abfb.png">

**Comment by dchaofei** [comment]
请按照 issue 模板，把环境、版本补充一下

**Comment by aiscrm** [comment]
**Runtime environment**
 - OS: MacOS
 - ARCH: amd64
 - Puppet: wxwork
 - Version: v0.4.2
 - GO: 1.18, 1.17

**Comment by dchaofei** [comment]
go-wechaty 版本?

**Comment by aiscrm** [comment]
go-wechaty的版本是v0.4.2，不知您还需要什么的版本？

**Comment by dchaofei** [comment]
好吧，你是通过 docker 启动的 wxwork 吗？如果是提供一下镜像版本给我，我之前还真没用过 wxwork

**Comment by aiscrm** [comment]
我是直接go run的

**Comment by aiscrm** [comment]
Makefile:

**Comment by dchaofei** [comment]
看来我要先去申请一个企业微信的 token

**Comment by dchaofei** [comment]
你能正常接收到小程序消息吗？并且获取到 title、description

**Comment by corelchen** [comment]
多谢。
wechaty/go-grpc层收到的小程序消息是正常的，wechaty/go-wechaty层的处理有问题，我改了一下可以了，要不要我提过pr啊

**Comment by aiscrm** [comment]
多谢。
wechaty/go-grpc层收到的小程序消息是正常的，wechaty/go-wechaty层的处理有问题，我改了一下可以了，要不要我提过pr啊

**Comment by dchaofei** [comment]
我应该知道问题所在了，我先提交个 pr，我这边没有 token，你帮忙测试一下哈

**Comment by aiscrm** [comment]
提交pr了，方便加个微信，我把我的token给你测试吗

**Comment by dchaofei** [comment]
我提交了一个 pr，你可以帮忙验证一下收发小程序的问题吗？ #130

**Comment by corelchen** [comment]
ok

**Comment by dchaofei** [comment]
> 提交pr了，方便加个微信，我把我的token给你测试吗

这是我的微信 dingchaofei123

**Comment by aiscrm** [comment]
> 我提交了一个 pr，你可以帮忙验证一下收发小程序的问题吗？ #130

验证可以了，非常感谢
