### ISSUE TITLE
关于群内企业微信用户发的图片

### ISSUE THREAD

**Issue by xiangyaoan** [wechaty/go-wechaty#134]
你好,现在对图片类型的获取只有 原图，高清图，压缩图。企业微信发的图片无法获取到，请问能支持吗？

**Comment by dchaofei** [comment]
什么 puppet ？

**Comment by dchaofei** [comment]
能回答下 issue 模板里的问题吗？

**Comment by xiangyaoan** [comment]
**Is your feature request related to a problem? Please describe.**
群图片获取，无法获取到企业微信用户发出的图片

**Describe the solution you'd like**
希望能正确获取到来自企业微信发送的图片

**Describe alternatives you've considered**
不知道还有什么获取方式

**Please rate Feature**
感觉这个挺重要 

**Additional context**
用的go-wechaty v0.4.3 + wechaty-puppet-padlocal + wechaty/wechaty:1.19

**Comment by dchaofei** [comment]
如果你提 issue 时能把 err 一起提供，肯定能定位问题会更快一下😁，我本地试了下，现在已经基本确定是 puppet-padlocal 的问题，你可以去 [puppet-padlocal](https://github.com/wechaty/puppet-padlocal)  项目提一个新的 issue，记得带上 err log

**Comment by xiangyaoan** [comment]
好的，感谢大佬
