### ISSUE TITLE
[BUG] 连接不上本地镜像

### ISSUE THREAD

**Issue by hailiangchen** [wechaty/go-wechaty#140]
版本：
wechaty/wechaty:0.78  ;  go-wechaty  0.4.6

环境变量：
$env:WECHATY_PUPPET_SERVICE_ENDPOINT="127.0.0.1:8788"

错误信息
```
PS D:\Share\go-wechaty> go run .\examples\ding-dong-bot.go
2022/11/02 20:29:58 PuppetService Start()
2022/11/02 20:29:58 PuppetService startGrpcStream() eventStream err rpc error: code = Unauthenticated desc = Invalid Wechaty TOKEN "xxxxxxx"
2022/11/02 20:29:58 puppet start err:  PuppetService Start() rejection: rpc error: code = Unauthenticated desc = Invalid Wechaty TOKEN "xxxxxx"
panic: PuppetService Start() rejection: rpc error: code = Unauthenticated desc = Invalid Wechaty TOKEN "xxxxxxx"

goroutine 1 [running]:
github.com/wechaty/go-wechaty/wechaty.(*Wechaty).DaemonStart(0xc000198240)
        D:/Share/go-wechaty/wechaty/wechaty.go:295 +0xc5
main.main()
        D:/Share/go-wechaty/examples/ding-dong-bot.go:29 +0x13c
exit status 2
```

**Comment by hailiangchen** [comment]
我得TOKEN 是正确的，wechaty 里面是登录成功得。可以看到我发送得消息

**Comment by dchaofei** [comment]
能看一下你是在哪传的 token 吗？

**Comment by hailiangchen** [comment]
docker run -it -d --name wechaty -e WECHATY_LOG="verbose" \
-e WECHATY_PUPPET="wechaty-puppet-padlocal" \
-e WECHATY_PUPPET_SERVICE_NO_TLS_INSECURE_SERVER=true \
-e WECHATY_PUPPET_SERVICE_NO_TLS_INSECURE_CLIENT=true 
-e WECHATY_PUPPET_PADLOCAL_TOKEN="puppet_padlocal_xxxxxxxx" \ 
-e WECHATY_PUPPET_SERVER_PORT="8788" -e WECHATY_TOKEN="1fe5f846-3cfb-401d-b20c" \
-p "8788:8788" wechaty/wechaty:0.78

**Comment by dchaofei** [comment]
docker run 没问题
只是 go-wechaty 忘记加 WECHATY_TOKEN 了

试试下边这样,  WECHATY_PUPPET_SERVICE_TOKEN 要和你 docker run 里的 WECHATY_TOKEN 一致
```
WECHATY_PUPPET_SERVICE_ENDPOINT=xxxxx WECHATY_PUPPET_SERVICE_TOKEN=1fe5f846-3cfb-401d-b20c go run .\examples\ding-dong-bot.go
```

**Comment by hailiangchen** [comment]
可以了。感谢
