### ISSUE TITLE
[BUG]  start service error

### ISSUE THREAD

**Issue by Garfield-yin** [wechaty/go-wechaty#145]
**Describe the bug**
 PuppetService Start() rejection: no endpoint

**Runtime environment**
 - OS: mac
 - ARCH: arm
 - go-wechaty v0.4.9
 
**Console output**
go run examples/ding-dong-bot.go
TRAC[2023-02-26 16:05:54.133] PuppetService Start()                         module=wechaty-puppet-service
ERRO[2023-02-26 16:05:54.941] discoverServiceEndPoint() err: http.Status:404 Not Found  module=wechaty-puppet-service
ERRO[2023-02-26 16:05:54.941] puppet start err: PuppetService Start() rejection: no endpoint  module=wechaty
panic: PuppetService Start() rejection: no endpoint

goroutine 1 [running]:
github.com/wechaty/go-wechaty/wechaty.(*Wechaty).DaemonStart(0x1400023e240?)
	/Users/fei/go/pkg/mod/github.com/wechaty/go-wechaty@v0.4.9/wechaty/wechaty.go:294 +0xc0
main.main()
	/Volumes/workspace/caixuan/cx-go-wechaty/examples/ding-dong-bot.go:44 +0xb4
exit status 2
make: *** [bot] Error 1

**Comment by dchaofei** [comment]
看起来是传的 token 不对
