### ISSUE TITLE
Go 版本的不支持 node 版本不需要 token 的启动？

### ISSUE THREAD

**Issue by af913337456** [wechaty/go-wechaty#147]
如题。node 版本的可以直接在本地跑，Go 的要 token。

**Comment by dchaofei** [comment]
是的 go 的都是需要 token

node 版本不需要 token 的 puppet 可以通过 wechaty gateway 转换一下生成假的 token 给 go 连

**Comment by Yeeyao** [comment]
> 是的 go 的都是需要 token
> 
> node 版本不需要 token 的 puppet 可以通过 wechaty gateway 转换一下生成假的 token 给 go 连

请问这里能提供相关的文档吗？

**Comment by dchaofei** [comment]
@Yeeyao https://wechaty.js.org/docs/puppet-services/diy/

**Comment by Yeeyao** [comment]
> @Yeeyao https://wechaty.js.org/docs/puppet-services/diy/

收到，感谢，建议补充到文档里面让大家参考

1. Go 版本的 puppet 一定需要一个 token，即便使用的是免费版本的 puppet
2. Go 版本的免费 puppet 所需要的 token 需要自行搭建服务来生成。[搭建服务参考文档](https://wechaty.js.org/docs/puppet-services/diy/)

**Comment by dchaofei** [comment]
收到，感谢建议，我补充到 readme
