### ISSUE TITLE
[BUG] start wechaty with WorkPro-token failed

### ISSUE THREAD

**Issue by KyoUK4n** [wechaty/go-wechaty#148]
**Describe the bug**
start wechaty with WorkPro-token failed

here is my code:
```
puppetOption := wechaty.WithPuppetOption(wp.Option{
		Timeout:  time.Second * 10,
		Token:                 "puppet_workpro_xxx",
		GrpcReconnectInterval: time.Second * 2,
	})
	wechatySer := wechaty.NewWechaty(puppetOption)

	wechatySer.
		OnScan(func(context *wechaty.Context, qrCode string, status schemas.ScanStatus, data string) {
			fmt.Printf("Scan QR Code to login: %s\nhttps://wechaty.github.io/qrcode/%s\n", status, qrCode)
		}).
		OnLogin(func(context *wechaty.Context, user *user.ContactSelf) {
			fmt.Printf("User %s logined\n", user)
		}).DaemonStart()
```

here is stack:
**Console output**
```
time="2023-04-04 18:13:10.566" level=error msg="puppet start err: PuppetService Start() rejection: startGrpcStream err:rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing: reading server HTTP response: unexpected EOF\"" module=wechaty
panic: PuppetService Start() rejection: startGrpcStream err:rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: reading server HTTP response: unexpected EOF"

goroutine 1 [running]:
github.com/wechaty/go-wechaty/wechaty.(*Wechaty).DaemonStart(0xc000000480)
	/home/projects/demo/vendor/github.com/wechaty/go-wechaty/wechaty/wechaty.go:294 +0x176
main.main()
	/home/projects/demo/services/wechaty/wechaty.go:84 +0x145
```

**Runtime environment**
 - OS: Linux
 - ARCH: amd64
 - Puppet: WorkPro
 - Version v0.4.9

i've tried access https://api.chatie.io/v0/hosties/puppet_workpro_xxxxx，and i can get correct response.

so, here is my question :
1. Is it because go-wechaty does not yet support workpro?
2. Is there any error in my configuration?

please help me solve this problem, thank you.

**Comment by dchaofei** [comment]
Thanks for the feedback, but I'm going to apply for a workpro token first, which may take some time, so you can see if wechaty in the typescript version can connect to wokpro

**Comment by dchaofei** [comment]
I just applied for a workPro token, and I can log in normally according to your sample code. Please confirm whether the workPro service where your token is located is normal. In addition, the QR code needs to be encoded.
```
fmt.Printf("https://wechaty.js.org/qrcode/%s", url.QueryEscape(qrCode))
```

**Comment by KyoUK4n** [comment]
Thanks for the reply. I just found out that I access the workPro service through the proxy. It can normally be accessed after closing the proxy.
