### ISSUE TITLE
[BUG] 邀请机器人进入40人以下的群聊触发OnRoomJoin获取不到机器人自己信息

### ISSUE THREAD

**Issue by deanxv** [wechaty/go-wechaty#150]
触发场景：

邀请机器人进入40人以下的群聊会直接入群，此时OnRoomJoin监听到，我想通过遍历inviteeList，并判断是否存在元素为机器人本身即是否为机器人入群。

触发环境：
padlocal
docker run wechaty:latest

代码片段：
```go
func OnRoomJoin(context *wechaty.Context, room *user.Room, inviteeList []_interface.IContact, inviter _interface.IContact, date time.Time) {
	fmt.Println("群成员新增触发-start")
	for _, contact := range inviteeList {
		fmt.Println(contact.ID())
		fmt.Println(contact.Weixin())
		fmt.Println(contact.Name())
		fmt.Println(contact.Self())
		if contact.Self() {
			fmt.Println("机器人自己入群")
		}
	}
	fmt.Println("群成员新增触发-end")
}
```

打印日志：
```
群成员新增触发-start
4eb25fc0-c15e-4f41-a821-0e0289198349


false
群成员新增触发-end
```

打印的ID不是机器人的微信id，weixin和name都为空，contact.Self()也为false，但我记得之前好像是可以正常打印的。

如果这种方案不行的话，那我如何在40人以下的群邀请机器人后，获取到当前是否为机器人自己入群。

**Comment by deanxv** [comment]
喂喂喂

**Comment by dchaofei** [comment]
padlocal 事件返回的 inviteeList 中的 id 看起来像是一个 uuid，应该返回 wx 用户 id 才对～，你可以提个 issue 到 padlocal

**Comment by deanxv** [comment]
> padlocal 事件返回的 inviteeList 中的 id 看起来像是一个 uuid，应该返回 wx 用户 id 才对～，你可以提个 issue 到 padlocal

已经加了padlocal客服的微信了，同意了好友申请但迟迟不回复消息。估计这个bug也不会再修复了T T
