### ISSUE TITLE
[BUG] Message.Date()返回的是毫秒数，不是时间戳。

### ISSUE THREAD

**Issue by jmjoy** [wechaty/go-wechaty#151]
**Describe the bug**
Message.Date()返回的是毫秒数，不是时间戳。

**To Reproduce**
1. OnMessage获得消息Message
2. 调用Date()方法，打印，得到"55535-03-27T07:46:36.000+0800"
3. 怀疑是毫秒数，于是`time.Unix(message.Date().Unix()/1000, 0)`，得到正确的“2023-07-26T15:13:56.000+0800”

**Expected behavior**
希望得到“2023-07-26T15:13:56.000+0800”

**Runtime environment**
 - OS: Linux
 - ARCH: amd64
 - Puppet: hostie
 - Version 0.4.9

**Comment by dchaofei** [comment]
如何重现，我这边没有复现到这个问题，我的环境是：
puppet： padlocal
wechaty-docker： wechaty/wechaty:1.20

**Comment by dchaofei** [comment]
你这边用的是什么 puppet，初步猜测是有些 puppet 返回的是秒，有些是毫秒

**Comment by jmjoy** [comment]
用的这个：https://wechaty.js.org/docs/puppet-services/workpro

错怪go的sdk了 :-(

**Comment by dchaofei** [comment]
我先去申请个 workpro 的 token～

**Comment by jmjoy** [comment]
> 我先去申请个 workpro 的 token～

牛批，敬业！

**Comment by dchaofei** [comment]
已做兼容处理，升级到 v0.4.10 可解决
