### ISSUE TITLE
收发红包

### ISSUE THREAD

**Issue by wetalice** [wechaty/go-wechaty#155]
非常棒的项目。我想用这个库实现红包收发，而不仅仅是信息的接收和回复。请问可以做到吗？

**Comment by dchaofei** [comment]
这个要依赖于你使用的 puppet，理论上 puppet 支持，go-wecahty 也可以支持

**Comment by wetalice** [comment]
> 这个要依赖于你使用的 puppet，理论上 puppet 支持，go-wecahty 也可以支持

原来如此，感谢🙏
