### ISSUE TITLE
[error]Unimplemented desc

### ISSUE THREAD

**Issue by jacsice** [wechaty/go-wechaty#156]
2023/12/02 16:20:04 2222 <nil> rpc error: code = Unimplemented desc = The server does not implement the method /wechaty.Puppet/MessageFileStream

这个是什么意思？

**Comment by dchaofei** [comment]
单纯的看错误日志是你所使用的 puppet 不支持你所做的操作，具体还需你提供一些补充信息

请提供以下信息:
- 使用的 puppet 是？如果 puppet 有版本也提供下
- go-wechaty 的版本？
- 如何复现这个错误？提供下最小能复现的代码段
