### ISSUE TITLE
[BUG] puppet start err: PuppetService Start() rejection: startGrpcStream err:rpc error: code = Unavailable desc = connection closed before server preface received  module=wechaty

### ISSUE THREAD

**Issue by xpsuper** [wechaty/go-wechaty#158]
直接拉的最新代码，然后运行的 examples 里面的 ding-dong-bot， 可以确保配置了正确的 Endpoint 和 Token，但一启动就报错：
puppet start err: PuppetService Start() rejection: startGrpcStream err:rpc error: code = Unavailable desc = connection closed before server preface received  module=wechaty

使用的gateway:

docker pull wechaty/wechaty

export WECHATY_LOG=verbose
export WECHATY_PUPPET=wechaty-puppet-padlocal
export WECHATY_PUPPET_PADLOCAL_TOKEN=puppet_padlocal_xxxxxx
export WECHATY_PUPPET_SERVER_PORT=8788
export WECHATY_TOKEN=puppet_padlocal_xxxxx

docker run -it \
--name wechaty_gateway \
--rm \
-e WECHATY_LOG \
-e WECHATY_PUPPET \
-e WECHATY_PUPPET_PADLOCAL_TOKEN \
-e WECHATY_PUPPET_SERVER_PORT \
-e WECHATY_TOKEN \
-p "$WECHATY_PUPPET_SERVER_PORT:$WECHATY_PUPPET_SERVER_PORT" \
wechaty/wechaty

无论 gateway 放本地 还是 服务器均报这个错误，可以确定网络及服务端口正常

**Comment by dchaofei** [comment]
禁用 gateway 的 tls，docker run 增加一个环境变量：
```
WECHATY_PUPPET_SERVICE_NO_TLS_INSECURE_SERVER = true
```
参考: https://github.com/wechaty/go-wechaty/issues/101
