### ISSUE TITLE
wechat4u

### ISSUE THREAD

**Issue by chenkaidog** [wechaty/go-wechaty#159]
请问如何使用wechat4u这个puppet呢？这个sdk支持吗？

**Comment by chenkaidog** [comment]
说错了，请问如何使用wechat4u这个puppet呢？这个sdk支持吗？

**Comment by dchaofei** [comment]
可以的，把 wechat4u 转换为 gateway 就可以用 go-wechaty 连了
参考： https://wechaty.js.org/docs/puppet-services/diy/

**Comment by chenkaidog** [comment]
> 可以的，把 wechat4u 转换为 gateway 就可以用 go-wechaty 连了 参考： https://wechaty.js.org/docs/puppet-services/diy/

thank you! let me try.
