### ISSUE TITLE
[Circler Dependencies]: import cycle not allowed

### ISSUE THREAD

**Issue by huan** [wechaty/go-wechaty#16]
We need to find a way to avoid the circle dependencies problem.

Current state: `make bot`

```sh
$ make bot
go run examples/ding-dong-bot.go
import cycle not allowed
package main
	imports github.com/wechaty/go-wechaty/wechaty
	imports github.com/wechaty/go-wechaty/wechaty/user
	imports github.com/wechaty/go-wechaty/wechaty
make: *** [Makefile:40: bot] Error 1
```

**Comment by dingdayu** [comment]
@huan I think we can close this issues.

**Comment by huan** [comment]
@dingdayu great!

Could you explain a little bit about how did we solve this problem for now?

**Comment by dingdayu** [comment]
@huan 

This is a mistake in the initial project structure. It is only a temporary problem and will not be encountered repeatedly.
