### ISSUE TITLE
【wechaty问题交流微信群】一起讨论，吐槽，解决wechaty中遇到的坑

### ISSUE THREAD

**Issue by suxiaobei1024** [wechaty/go-wechaty#166]
![程序元阿维-个人微信-二维码](https://github.com/wechaty/go-wechaty/assets/11757587/58248575-27d9-4708-91d4-db5a7a1a16dd)

加我vx: pixes6688
一起交流问题，
备注: wechaty-xxx

**Comment by dingdayu** [comment]
Hi, @suxiaobei1024 我觉得这可能不是一个合适的 issue 的使用方式，你可以在相关讨论下留下个人信息以吸引更多的志同道合者，单独的联系方式帖子颇受争议，我将 Close 这个 issue。
