### ISSUE TITLE
[BUG]wechaty/wechaty:1.20 现在扫码无法登录，无限循环提示扫码登录连接 

### ISSUE THREAD

**Issue by wordgao** [wechaty/go-wechaty#169]
wechaty/wechaty:1.20 现在扫码无法登录，无限循环提示扫码登录连接
go-wechaty v0.4.12
puppter 是运行正常的环境复制并修改关键必要字段后的环境。
目前不知道是什么地方出现问题了。
换了ID也没用，一直重复提示扫码登录，扫码登录确认后也是继续循环提示扫码登录。

---------------
![截图 2024-10-31 08-57-24](https://github.com/user-attachments/assets/7d55d168-0f4b-428f-a546-89e30177cd2f)

**Comment by wordgao** [comment]
puppet类型 puppet_padlocal

WECHATY_PUPPET_PADLOCAL_TOKEN=puppet_padlocal_xxxx................

**Comment by dchaofei** [comment]
puppet_padlocal 的问题，https://github.com/wechaty/puppet-padlocal/issues/326
