### ISSUE TITLE
demo Run fild in mac

### ISSUE THREAD

**Issue by shuyabin** [wechaty/go-wechaty#34]
![image](https://user-images.githubusercontent.com/14884581/79726832-00914780-831e-11ea-94f4-ed3c72600916.png)
![image](https://user-images.githubusercontent.com/14884581/79727155-81e8da00-831e-11ea-942c-293a2997e2f3.png)

**Comment by dchaofei** [comment]
master branch now can not run, you can switch to the puppet-hostie branch, we will support the master branch as soon as possible.

**Comment by dingdayu** [comment]
@shuyabin 

The `puppet-hostie` branch has been merged into `master`. If you have a `hostile token`, you can already test it. If you cannot succeed, you may get some help here.

#32

**Comment by shuyabin** [comment]
thanks   
I want to know How  to apply   hostile token

**Comment by huan** [comment]
To get a hostie token  you can apply for the donut alpha testers program at https://github.com/wechaty/wechaty/issues/1941
