### ISSUE TITLE
contact.alias() 拆分为 get 和 set

### ISSUE THREAD

**Issue by dchaofei** [wechaty/go-wechaty#43]
在 ts 版本中:
- alias() 代表 get
- alias(newAlias) 代表 set
- alias(null) 代表 delete

但是在 go 语言里边参数是必传的，所以我准备把 alias 拆分为两个方法。
- GetAlias() 代表 get
- SetAlias("newAlias") 代表 set
- SetAlias("") 代表 delete

这样做是否可以? @huan

**Comment by huan** [comment]
According to <https://golang.org/doc/effective_go.html#Getters> and <https://stackoverflow.com/a/11810342/1123955>, how about let's use `Alias()` as the getter, and `SetAlias()` as the setter, which can maximumly align to the TS API?

**Comment by dchaofei** [comment]
好的，我会用 `Alias()` and `SetAlias()`
