### ISSUE TITLE
Shall we use the go-wechaty repo as a publish-only repo?

### ISSUE THREAD

**Issue by huan** [wechaty/go-wechaty#50]
The Go Wechaty will be installed from `github.com/wechaty/go-wechaty`, so the `wechaty/go-wechaty` is our deploy repo for the Go Lang.

### The Problem

However, currently, we are developing based on this repo too, which makes it complicated to maintain and not very clean.

### The Solution

Shall we use this `wechaty/go-wechaty` for our publish-only repo, and we deploy the code from our developing repo to this publish-only repo by DevOps & CI/CD? That would help us make sure the published code is with high quality as we expected.

### RFC

For the simplest way to archive this goal, we can just rename `wechaty/go-wechaty` to another name which can stands for the developing, like `wechaty/go-wechaty-src` (good suggestions are welcome!), and then create a new repo named `wechaty/go-wechaty` for the deployment.

If we think it's necessary to continue this discussion, please feel free to share your thoughts by commenting on this issue, thank you very much!

**Comment by dingdayu** [comment]
About deploy repo:

In a Git Repository with Tags, `go get ...` Get the latest Tag automatically.

Test:
```
mkdir test
cd test
go mod init test
go get github.com/wechaty/go-wechaty
```
Output:
```
go: downloading github.com/wechaty/go-wechaty v0.1.0
go: github.com/wechaty/go-wechaty upgrade => v0.1.0
```

Git repository without tag，will be used commute id

**Comment by dingdayu** [comment]
There is already an answer, and for some time, so close it.
