### ISSUE TITLE
Suggest to stop auto rewriting code in the PR

### ISSUE THREAD

**Issue by huan** [wechaty/go-wechaty#52]
Currently, we are doing a code rewrite and commit automatically in every PR:

```sh
github-actions bot commented 24 minutes ago
🚀 Your go files have been formatted successfully
```

I'd like to change this behavior from rewrite automatically to throw a failure via CI if the code has not been formatted as expected, which can leave the responsibility of the code formatting to the PR author.

Another benefit after this change is that we can also keep our contributor record clean because it can prevent lots of unnecessary commits.

**Comment by huan** [comment]
ping @dingdayu: I'm looking forward to hearing from you and moving forward to fix this issue.

Thank you very much!

**Comment by dingdayu** [comment]
Oh,very sorry, I ignored this message.

Does it mean that CI only checks and does not automatically format the submitter?

**Comment by huan** [comment]
Yes. I believe we should only check the code, and fail the CI if the code is not well-formatted because it would be better to leave the final fix work to the original PR submitter.

**Comment by dingdayu** [comment]
OK,I also hesitated about this.

At #48 , I removed the auto format, update codeclimate config.

Regarding fmt checking, we can rely on codeclimate.

Example: https://github.com/dingdayu/go-wechaty/pull/10

**Comment by huan** [comment]
Great, thanks for updating.

We should make sure the message be clear for the developers when the CI failed a PR.

We can continue to iterate our GitHub Actions to make it better.

**Comment by dingdayu** [comment]
@huan In addition to the need to update the configuration file, you also need to enable the `Code Climate features on GitHub` in the codeclimate.

**Comment by huan** [comment]
Updated. 

Please feel free to let me know if there needs any other setup.

![image](https://user-images.githubusercontent.com/1361891/83132158-8ff6fb00-a113-11ea-9bb2-0ead5abef26c.png)
