### ISSUE TITLE
[Feature]Add grpc.default_authority option for authorization

### ISSUE THREAD

**Issue by jcai** [wechaty/go-wechaty#69]
**Is your feature request related to a problem? Please describe.**
Some gRPC server  use `token` to identify the current user in the same service port.

**Describe the solution you'd like**
add `grpc.default_authority` option to grpc channel

see:
https://github.com/wechaty/wechaty-puppet-hostie/pull/78

**Comment by huan** [comment]
@jcai please help us to close this issue if all your feature request have been satisfied.

Thank you very much!

**Comment by dchaofei** [comment]
@jcai 我为 go-wechaty 加了 grpc.default_authority, 我需要怎么测试一下？

**Comment by jcai** [comment]
在开发者群里面，联系我一下

**Comment by jcai** [comment]
或者给我你的微信号

**Comment by huan** [comment]
I'd like to suggest that we should keep the discussion on GitHub as possible as we can because it will let everyone to know what happened so that they will be able to join if they can contribute.

**Comment by dchaofei** [comment]
向 @jcai 要了个 token, 测试没问题，可以正常使用蔡大提供的 puppet 服务，稍后我将关闭这个 issue

**Comment by huan** [comment]
Fantastic!

So glad to know that our Go Wechaty is ready to use Puppet Rock Service from @jcai , and appreciate for your contribution @dchaofei !

**Comment by jcai** [comment]
@dchaofei Thank you very much,If you have any questions about rock service,please let me know!
