### ISSUE TITLE
[Feature]Design a plug-in to provide HTTP API service for go-wechaty

### ISSUE THREAD

**Issue by SilkageNet** [wechaty/go-wechaty#75]
设计一个go-wechaty插件，提供HTTP API服务以管理Wechaty的各种功能。有了完善的基础API服务后，后面可根据API做可视化界面、cli、第三方服务等。

**Comment by dchaofei** [comment]
@SilkageNet 这个 feature 是留给 summer-of-wechaty 的学生们做的吗？
