### ISSUE TITLE
WECHATY_LOG environment variable specification (valid values)

### ISSUE THREAD

**Issue by huan** [wechaty/go-wechaty#77]
According to our Wechaty Specification <https://wechaty.js.org/docs/specs/wechaty>:

The `WECHATY_LOG` should support the values of `silly`, `verbose`, `info`, `warn`, `silent`

All Polyglot Wechaty should at least support the above names as an alias.

Link to https://github.com/wechaty/wechaty/issues/2167

**Comment by XRSec** [comment]
希望能抽空添加
WECHATY_PUPPET
WECHATY_TOKEN
WECHATY_PUPPET_SERVICE_TOKEN
WECHATY_PUPPET_SERVER_PORT
WECHATY_PUPPET_SERVICE_NO_TLS_INSECURE_SERVER

```go
wp "github.com/wechaty/go-wechaty/wechaty-puppet"
	var bot = wechaty.NewWechaty(wechaty.WithPuppetOption(wp.Option{
		Endpoint:      "127.0.0.1:30009",
		Token:         "2fdb00a5-5c31-4018-84ac-c64e5f995057",
		SERVICE_TOKEN: "",
		NO_TLS:        true,
		TLS:           "",
		Timeout:       2 * time.Minute,
	}))```
