### ISSUE TITLE
[BUG] 无法获取到图片信息

### ISSUE THREAD

**Issue by wordgao** [wechaty/go-wechaty#85]
源码：
// ToImage extract the Image File from the Message, so that we can use different image sizes.
func (m *Message) ToImage() (_interface.IImage, error) {
	if m.Type() != schemas.MessageTypeImage {
		return nil, errors.New("not a image type message")
	}
	return m.GetWechaty().Image().Create(m.id), nil
}

测试。。。。。。

方式一
img,_:=message.ToImage()
fmt.Println(img.HD())
获取不到任何图片信息

方式二
img,_:=message.ToFileBox()
fmt.Println(img.ToDataURL())

无法获取到图片信息

**Comment by dchaofei** [comment]
你能贴下错误信息吗？

img.HD() 会返回一个 *file_box.FileBox 和 error, 

如果没有 error，你就可以调用 FileBox 的 ToFile 方法把图片转为文件存储。

**Comment by wordgao** [comment]
没有错误，可以获取到base64和文件名了，但获取不到dataurl。

**Comment by dchaofei** [comment]
你应该是对 dataurl 有一些误解，我猜你是想获取一个图片的网络地址，这需要你自己把图片的数据上传到云存储

这里有对 dataurl 的解释: https://developer.mozilla.org/zh-CN/docs/Web/HTTP/Basics_of_HTTP/Data_URIs

**Comment by wordgao** [comment]
感谢，问题已解决，依然有一个小小的bug不知道为何不支持链式操作，
正常情况下应该是在HD后面可以直接得到todataurl或者是base64的文件信息的，
但这里依然要重新获取并判断nil后才能tobase64或todataurl

**Comment by dchaofei** [comment]
这个就是错误处理了，因为HD()方法也是根据消息id然后远程调用获取图片数据的，可能会出现调用失败

或者你有更好的处理方式，可以拿出来一起讨论，优化框架
