### ISSUE TITLE
登录一段时间微信会自动退出

### ISSUE THREAD

**Issue by xiaoming902** [wechaty/go-wechaty#86]
这几天运行发现隔个二三天左右微信账号就会自动退出，这种自动退出后，是否可以设置自动登录或者怎么不自动退出登录？在手机微信端无任何操作
docker日志
21:48:07 VERB EventStreamManager grpcEmit(EVENT_TYPE_HEARTBEAT[1], {"data":"heartbeat@browserbridge ding"})
21:48:22 VERB EventStreamManager grpcEmit(EVENT_TYPE_HEARTBEAT[1], {"data":"heartbeat@browserbridge ding"})
21:48:32 VERB PuppetWeChatBridge onLoad() page.url=https://wx2.qq.com/?&lang=en
21:48:32 VERB PuppetWeChatBridge readyAngular()
21:48:32 VERB PuppetWeChatBridge inject()
21:48:32 VERB EventStreamManager grpcEmit(EVENT_TYPE_HEARTBEAT[1], {"data":"heartbeat@browserbridge ding"})
21:48:32 VERB PuppetWeChatBridge ding(ding() OK!)
21:48:32 VERB EventStreamManager grpcEmit(EVENT_TYPE_DONG[3], {"data":"ding() OK!"})
21:48:32 VERB PuppetWeChatBridge clickSwitchAccount()
21:48:33 VERB PuppetWeChatEvent onScan({code: 0, url: https://login.weixin.qq.com/qrcode/QaUgZVng2g==})
21:48:33 VERB MemoryCard set(PUPPET_WECHAT, [object Object],[object Object],[object Object],[object Object],[object Object],[object Object])
21:48:33 VERB MemoryCard save() to StorageFile</wechaty/e4604ef1-f823-bd1f-3e6d-cebd84842d9d.memory-card.json>
21:48:33 VERB StorageFile save() to /wechaty/e4604ef1-f823-bd1f-3e6d-cebd84842d9d.memory-card.json
21:48:33 VERB PuppetWeChatEvent onScan() there has user when got a scan event. emit logout and set it to null
21:48:33 VERB PuppetWeChat logout()
21:48:33 VERB Puppet selfId()
21:48:33 VERB PuppetWeChatBridge logout()
21:48:33 VERB EventStreamManager grpcEmit(EVENT_TYPE_LOGOUT[26], {"contactId":"@0bac3b4fe04e292c879bf1013577feb27b98c3dd8aaad177d4c7cf7173842a56","data":"logout()"})
21:48:33 VERB ContactSelf name()
21:48:33 INFO IoClient 哈 logged out
21:48:33 VERB EventStreamManager grpcEmit(EVENT_TYPE_HEARTBEAT[1], {"data":{"code":0,"url":"https://login.weixin.qq.com/qrcode/QaUgZVng2g=="},"type":"scan"})
21:48:33 INFO IoClient [2] https://login.weixin.qq.com/l/QaUgZVng2g==
Online QR Code Image: https://wechaty.js.org/qrcode/https%3A%2F%2Flogin.weixin.qq.com%2Fl%2FQaUgZVng2g%3D%3D
21:48:33 VERB EventStreamManager grpcEmit(EVENT_TYPE_SCAN[22], {"qrcode":"https://login.weixin.qq.com/l/QaUgZVng2g==","status":2})
21:48:34 VERB PuppetWeChatBridge onLoad() page.url=https://wx2.qq.com/?&lang=en
21:48:34 VERB PuppetWeChatBridge readyAngular()
21:48:34 VERB PuppetWeChatBridge inject()
21:48:34 VERB EventStreamManager grpcEmit(EVENT_TYPE_HEARTBEAT[1], {"data":"heartbeat@browserbridge ding"})
21:48:34 VERB PuppetWeChatBridge ding(ding() OK!)
21:48:34 VERB EventStreamManager grpcEmit(EVENT_TYPE_DONG[3], {"data":"ding() OK!"})
21:48:34 VERB PuppetWeChatBridge clickSwitchAccount()

ding-dong 机器人日志：
2021/06/23 05:48:32 PuppetService onGrpcStreamEvent({type:EVENT_TYPE_HEARTBEAT payload:{"data":"heartbeat@browserbridge ding"}})
2021/06/23 05:48:32 PuppetService onGrpcStreamEvent({type:EVENT_TYPE_DONG payload:{"data":"ding() OK!"}})
2021/06/23 05:48:33 PuppetService onGrpcStreamEvent({type:EVENT_TYPE_LOGOUT payload:{"contactId":"@0bac3b4fe04e292c879bf1013577feb27b98c3dd8aaad177d4c7cf7173842a56","data":"logout()"}})
User Contact<哈> logouted: logout()
2021/06/23 05:48:33 PuppetService onGrpcStreamEvent({type:EVENT_TYPE_SCAN payload:{"qrcode":"https://login.weixin.qq.com/l/QaUgZVng2g==","status":2}})
Scan QR Code to login: ScanStatusWaiting
https://wechaty.js.org/qrcode/https://login.weixin.qq.com/l/QaUgZVng2g==
2021/06/23 05:48:33 PuppetService onGrpcStreamEvent({type:EVENT_TYPE_HEARTBEAT payload:{"data":{"code":0,"url":"https://login.weixin.qq.com/qrcode/QaUgZVng2g=="},"type":"scan"}})
2021/06/23 05:48:33 PuppetService unMarshal err: json: cannot unmarshal object into Go struct field BaseEventPayload.Data of type string
2021/06/23 05:48:34 PuppetService onGrpcStreamEvent({type:EVENT_TYPE_HEARTBEAT payload:{"data":"heartbeat@browserbridge ding"}})
2021/06/23 05:48:34 PuppetService onGrpcStreamEvent({type:EVENT_TYPE_DONG payload:{"data":"ding() OK!"}})
2021/06/23 05:48:35 PuppetService onGrpcStreamEvent({type:EVENT_TYPE_SCAN payload:{"qrcode":"https://login.weixin.qq.com/l/AdN2-vpRtQ==","status":2}})
Scan QR Code to login: ScanStatusWaiting
https://wechaty.js.org/qrcode/https://login.weixin.qq.com/l/AdN2-vpRtQ==
2021/06/23 05:48:35 PuppetService onGrpcStreamEvent({type:EVENT_TYPE_HEARTBEAT payload:{"data":{"code":0,"url":"https://login.weixin.qq.com/qrcode/AdN2-vpRtQ=="},"type":"scan"}})
2021/06/23 05:48:35 PuppetService unMarshal err: json: cannot unmarshal object into Go struct field BaseEventPayload.Data of type string
2021/06/23 05:48:49 PuppetService onGrpcStreamEvent({type:EVENT_TYPE_HEARTBEAT payload:{"data":"heartbeat@browserbridge ding"}})

**Comment by dchaofei** [comment]
自动退出登录可能和微信的机制或者使用的 puppet 有关

**Comment by xiaoming902** [comment]
> 自动退出可能和微信的机制或者使用的傀儡

好吧，谢谢。那有什么办法可以退出后再自动登录吗

**Comment by dchaofei** [comment]
我理解一般自动退出就可能是微信踢下线了，这种需要扫码登录，你这边可以写代码监控 onscan 事件向你发送邮件或其他即时通知方式

还有一种比如 bot 所在的服务器挂了，这种微信还没退出登录，可以自动登录不需要扫码

**Comment by dchaofei** [comment]
> > 自动退出可能和微信的机制或者使用的傀儡
> 
> 好吧，谢谢。那有什么办法可以退出后再自动登录吗

@huan 这种有什么解决办法吗？我不太清楚 puppet 的实现方式

**Comment by huan** [comment]
Yes, it still highly depends on the implementation of the puppet service.

Please contact the puppet service provider support, see https://wechaty.js.org/docs/puppet-services/
