### ISSUE TITLE
[BUG] message.toRecalled() Unable to get recall message

### ISSUE THREAD

**Issue by Turbolisten** [wechaty/go-wechaty#87]
![image](https://user-images.githubusercontent.com/29906319/124767765-af916180-df6a-11eb-8472-6ec4fac4050d.png)

help ~

**Comment by dchaofei** [comment]
hi~, 我想知道你是用的什么 puppet， padlocal吗？

**Comment by dchaofei** [comment]
已修复，请升级到最新的版本
