### ISSUE TITLE
[BUG]使用go ding-dong-bot无法连接上padlocal本地服务

### ISSUE THREAD

**Issue by chasonnchen** [wechaty/go-wechaty#92]
请教，使用的是最新版代码，本地docker 部署的padlocal服务已登录运行正常。
本地运行ding-dong-bot， 报错无法连接上服务，请大佬帮看下

错误输出：
![image](https://user-images.githubusercontent.com/74540195/131484167-fe7062ee-3813-4e90-a971-ec9eab89c95b.png)

docker启动配置：
![image](https://user-images.githubusercontent.com/74540195/131484397-a8b49b19-b094-4039-b577-327b9e4689b4.png)

本地环境变量配置：
![image](https://user-images.githubusercontent.com/74540195/131484503-8848eae7-7e82-4f1d-bc1d-935c823c37cf.png)

请大佬指点。

**Comment by huan** [comment]
If you are using the latest Wechaty (0.68+), then you are running into https://github.com/wechaty/wechaty-puppet-service/issues/160

**Comment by chasonnchen** [comment]
> If you are using the latest Wechaty (v0.68+), then you are running into [wechaty/wechaty-puppet-service#160](https://github.com/wechaty/wechaty-puppet-service/issues/160)

thx !
The problem is solved。

**Comment by huan** [comment]
Great to know that, and you are welcome!
