### ISSUE TITLE
使用message.Forward(room.ID())和message.ToFileBox()时，消息类型如果是image和video都报错：“json: cannot unmarshal string into Go struct field FileBoxOptions.headers of type []string”。

### ISSUE THREAD

**Issue by shenly2002** [wechaty/go-wechaty#93]
使用的是web协议，DIY Puppet Service：
export WECHATY_LOG="verbose"
export WECHATY_PUPPET="wechaty-puppet-wechat"
export WECHATY_PUPPET_SERVER_PORT="9999"
export WECHATY_TOKEN=“My token”
docker run \
  -d \
  -ti \
  --name wechaty_puppet_service_token_gateway \
  --rm \
  --privileged \
  --network=host \
  -e WECHATY_LOG \
  -e WECHATY_PUPPET \
  -e WECHATY_PUPPET_SERVER_PORT \
  -e WECHATY_TOKEN \
  wechaty/wechaty

在使用message.Forward(room.ID())和message.ToFileBox()时，消息类型是text没问题，消息类型是image和video时都报：“json: cannot unmarshal string into Go struct field FileBoxOptions.headers of type []string”这个错误，其他类型没测试，有解决办法吗，谢谢。
go version:1.17

**Comment by dchaofei** [comment]
临时修复，待有时间优化代码
