### ISSUE TITLE
[Feature] Can ContactPayload increase the Uin field?

### ISSUE THREAD

**Issue by li-xunhuan** [wechaty/go-wechaty#97]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Please rate Feature**
Please consider the scope of application and the difficulty of development.

**Additional context**

**Comment by dchaofei** [comment]
可以详细描述一下吗？

**Comment by li-xunhuan** [comment]
就是在这儿加一个Uin字段，那个字段是web微信的唯一标识，但是只有当前登录账号有，好友列表等是没有的。
或者可以复用一下Weixin那个字段，在那个字段存Uin。
我现在有个场景，我基于go-wechay做了个工具，里面有多个wechaty对象，有消息来了我不太能正确区分是哪个账号来的消息，因为我endpoint要是重新登录过之后，那个@开头的标示字符串就会发生变化，就匹配不上了！

![image](https://user-images.githubusercontent.com/10476982/132971045-56541d48-dccc-46d0-8881-88b33118f814.png)

**Comment by li-xunhuan** [comment]
说起来，还有一个点，这个不能标记消息为已读嘛？手机上的小红点会一直存在，标记之后小红点会没有了。

**Comment by dchaofei** [comment]
go-wechaty 依赖于 grpc 返回的结果，目前来看没有 uin 字段，你可以给 Wechaty 设置 name 属性来区分账号 https://github.com/wechaty/go-wechaty/blob/aee8757cd2c583378349f8ea8adb156b54175f4d/wechaty/option.go#L11

**Comment by huan** [comment]
> 说起来，还有一个点，这个不能标记消息为已读嘛？手机上的小红点会一直存在，标记之后小红点会没有了。

Please watch https://github.com/wechaty/wechaty/issues/2166 if you are interested in the `conversationalReadMark()` API.

**Comment by huan** [comment]
> 就是在这儿加一个Uin字段，那个字段是web微信的唯一标识，但是只有当前登录账号有，好友列表等是没有的。

There is a `Uin` property in the Web Protocol schema at https://github.com/wechaty/wechaty-puppet-wechat/blob/9c7b34e18eb74b90b6d1f609c7a7873b398170ac/src/web-schemas.ts#L28

I'd like to accept a Pull Request if you can pass it our and make it useful.

**Comment by li-xunhuan** [comment]
> go-wechaty 依赖于 grpc 返回的结果，目前来看没有 uin 字段，你可以给 Wechaty 设置 name 属性来区分账号
> 
> https://github.com/wechaty/go-wechaty/blob/aee8757cd2c583378349f8ea8adb156b54175f4d/wechaty/option.go#L11

我设置了Name属性之后，在OnMessage回调函数里面怎么取出来啊？

**Comment by dchaofei** [comment]
> > go-wechaty 依赖于 grpc 返回的结果，目前来看没有 uin 字段，你可以给 Wechaty 设置 name 属性来区分账号
> > https://github.com/wechaty/go-wechaty/blob/aee8757cd2c583378349f8ea8adb156b54175f4d/wechaty/option.go#L11
> 
> 我设置了Name属性之后，在OnMessage回调函数里面怎么取出来啊？

message.GetWechaty().(*wechaty.Wechaty).Name()

**Comment by li-xunhuan** [comment]
> message.GetWechaty().(*wechaty.Wechaty).Name()

感谢！！


`话说，心跳日志能不能不打啊，满屏全是，筛选有效信息太困难了`

**Comment by dchaofei** [comment]
目前日志系统还待优化，你有什么想法可以提个pr，一起优化哈，比如设置日志等级等

**Comment by li-xunhuan** [comment]
> 目前日志系统还待优化，你有什么想法可以提个pr，一起优化哈，比如设置日志等级等

![a6a681ebgy1gp0onlivkjg206y06yjxs](https://user-images.githubusercontent.com/10476982/133010507-415212f1-5d33-43cf-bc4b-32865915bf22.gif)
